Controllers/SupplierController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RFIApp.Models;
using RFIApp.ViewModel;
using System;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using System.Reflection.Metadata.Ecma335;
using System.Text;
using Microsoft.Extensions.FileProviders;
using System.IO;
using System.Net.Mail;
using RFIApp.Helper;
using Microsoft.Extensions.Options;

namespace RFIApp.Controllers {
    public class SupplierController : Controller {
        private readonly SupplierContext _context;
        private IWebHostEnvironment _hostingEnvironment;
        private readonly IOptions<AttachmentSettings> attachmentOptions;
        private readonly AttachmentSettings attachmentSettings;
        public SupplierController(SupplierContext context, IWebHostEnvironment hostingEnvironment, IOptions<AttachmentSettings> Attachmentoptions, AttachmentSettings attachmentSettings) {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            attachmentOptions = Attachmentoptions;
            this.attachmentSettings = attachmentSettings;
        }
        public IActionResult Edit([FromQuery] Guid ID) {
            var SupplierGuid = _context.Suppliers.Find(ID);
                if (ID != Guid.Empty) {
                var viewModel = new SupplierViewModel {
                    BusinessTypes = Enum.GetValues(typeof(TypeOfBusiness))
                               .Cast<TypeOfBusiness>()
                               .Select(typeofBusiness => new SelectListItem {
                                   Text = typeofBusiness.GetDescription(),
                                   Value = ((int)typeofBusiness).ToString()
                               }).ToList(),
                };
                var ContactType = Enum.GetValues(typeof(ContactType))
                               .Cast<ContactType>()
                               .Select(ContactType => new SelectListItem {
                                   Text = ContactType.GetDescription(),
                                   Value = ((int)ContactType).ToString()
                               }).ToList();
                //viewModel.createContactModels[0].TypeOfContact = ContactType;
                viewModel.ContactTypeOptions = ContactType;
                viewModel.IsLocked = SupplierGuid.IsLocked;
                var SupplierData = _context.Suppliers.Find(ID);
                if (SupplierData == null) {
                    // return RedirectToAction("Edit");
                    return Json(new { Message = "Invalid Url " });
                }
                if (SupplierData.LegalName != null) {
                    viewModel.LegalName = SupplierData.LegalName;
                    viewModel.TypeOfBusiness = SupplierData.TypeOfBusiness ?? 0;
                    viewModel.TradingName = SupplierData.TradingName;
                    viewModel.CompanyAddress = SupplierData.CompanyAddress;
                    viewModel.PostalAddress = SupplierData.PostalAddress;
                    viewModel.TelephoneNumber = SupplierData.TelephoneNumber;
                    viewModel.WebAddress = SupplierData.WebAddress;
                    viewModel.PostCode = SupplierData.PostCode;
                    viewModel.FaxNumber = SupplierData.FaxNumber;
                    viewModel.EmployeesAreSubscribedToSocialSecurity = SupplierData.EmployeesAreSubscribedToSocialSecurity;
                    viewModel.NoOfEmployees = SupplierData.NoOfEmployees;
                    viewModel.IsLocked = SupplierData.IsLocked;
                    viewModel.FileAttachmentPath = SupplierData.FileAttachmentPath;
                    viewModel.FileAttachmentName = SupplierData.FileAttachmentName;
                }
                //Bank

                var supplierBankData = _context.BankDetails.Where(b => b.SupplierID == SupplierData.SupplierID).ToList();
                if (supplierBankData.Count() != 0) {
                    viewModel.createBankDetails = supplierBankData
                    .Select(b => new CreateBankDetailsModel {
                        BankName = b.BankName,
                        BeneficiaryName = b.BeneficiaryName,
                        SwiftBIC = b.SwiftBIC,
                        BankAccountNo = b.BankAccountNo,
                        BankAddress = b.BankAddress,
                        IBAN = b.IBAN,
                        AccountCurrency = b.AccountCurrency,
                        PaymentTerm = b.PaymentTerm,
                        BankDetailsID = b.BankDetailsID,

                    }).ToList();
                }

                //contact

                var supplierConatctData = _context.Contacts.Where(c => c.SupplierID == SupplierData.SupplierID).ToList();
                if (supplierConatctData.Count() != 0) {
                    viewModel.createContactModels = supplierConatctData
                  .Select(c => new CreateContactModel {
                      ContactType = c.ContactType,
                      ContactName = c.ContactName,
                      ContactTelNo = c.ContactTelNo,
                      EmailAddress = c.EmailAddress,
                      ContactID = c.ContactID,
                  }).ToList();
                }
                //production
                var supplierProductrionData = _context.ProductionInformation.Where(p => p.SupplierID == SupplierData.SupplierID).ToList();
                if (supplierProductrionData.Count() != 0) {
                    viewModel.createProductrion = supplierProductrionData
                   .Select(p => new CreateProductrionInformationModel {
                       ProductionCapacity = p.ProductionCapacity,
                       ExportCapacity = p.ExportCapacity,
                       Item = p.Item,
                       ProductionInformationID = p.ProductionInformationID,

                   }).ToList();
                }
                viewModel.SupplierID = ID;
                return View(viewModel);
            }
            else {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SupplierViewModel model, IFormFile file) {
            //var supplier = _context.Suppliers.Where(s=>s.SupplierID == model.SupplierID).FirstOrDefault();
            //bool IsLocked = supplier.IsLocked;
            if (model.IsLocked != true) {
                using var transaction = _context.Database.BeginTransaction();
                try {
                    // Save the form data to the database
                    var supplier = new Supplier {
                        SupplierID = model.SupplierID,
                        LegalName = model.LegalName,
                        TradingName = model.TradingName,
                        CompanyAddress = model.CompanyAddress,
                        PostalAddress = model.PostalAddress,
                        TelephoneNumber = model.TelephoneNumber,
                        WebAddress = model.WebAddress,
                        PostCode = model.PostCode,
                        FaxNumber = model.FaxNumber,
                        TypeOfBusiness = model.TypeOfBusiness,
                        NoOfEmployees = model.NoOfEmployees,
                        EmployeesAreSubscribedToSocialSecurity = model.EmployeesAreSubscribedToSocialSecurity,
                    };
                    if (model.FileAttachment != null) {

                    }
                    // supplier.Contacts = new List<Contact>();
                    //foreach (var item in model.createContactModels)
                    for (int i = 0; i < model.createContactModels.Count; i++) {
                        var item = model.createContactModels[i];
                        if (item.ContactID == Guid.Empty) {
                            for (int j = i + 1; j < model.createContactModels.Count; j++) {
                                var nextItem = model.createContactModels[j];

                                bool Isduplicated = (item.ContactType == nextItem.ContactType &&
                                                     item.ContactTelNo == nextItem.ContactTelNo &&
                                                     item.ContactName == nextItem.ContactName &&
                                                     item.EmailAddress == nextItem.EmailAddress);

                                if (Isduplicated) { return Json(new { success = false, message = "Data submitted Is Not Valid! Contact Data Submitted duplicated!" }); }
                            }
                        }
                        var existingContact = _context.Contacts.FirstOrDefault(bd => bd.ContactID == item.ContactID);
                        bool IsExisted = _context.Contacts.Where(a => a.SupplierID == model.SupplierID && a.ContactType == item.ContactType
                        && a.ContactName == item.ContactName && a.ContactTelNo == item.ContactTelNo && a.EmailAddress == item.EmailAddress).Any();
                        if (existingContact == null && item.IsDeleted == false && IsExisted == false) {
                            _context.Contacts.Add(new Contact {
                                SupplierID = supplier.SupplierID,
                                ContactType = item.ContactType,
                                ContactName = item.ContactName,
                                ContactTelNo = item.ContactTelNo,
                                EmailAddress = item.EmailAddress,
                            });

                        }
                        else if (existingContact != null && item.IsDeleted == false && IsExisted == false) {
                            existingContact.ContactTelNo = item.ContactTelNo;
                            existingContact.ContactType = item.ContactType;

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SUPPLIER REQUEST FOR INFORMATION FORM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <h2>SUPPLIER REQUEST FOR INFORMATION FORM</h2>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*  <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Create">Create New :</a>
                        </li>*@
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                   
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       @* <div class="container">
            &copy; 2023 - SupplierFormApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SUPPLIER REQUEST FOR INFORMATION FORM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/StyleSheet.css" />
    <link href="~/lib/sweetalert2/sweetalert2.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <h2>SUPPLIER REQUEST FOR INFORMATION FORM</h2>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*  <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Create">Create New :</a>
                        </li>*@
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
       @* <div class="container">
            &copy; 2023 - SupplierFormApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>*@
    </footer>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>